---
- name: Windows Update kényszerített kereséssel
  hosts: all
  gather_facts: false

  tasks:
    - name: Windows Update keresés indítása
      ansible.windows.win_shell: |
        UsoClient StartScan
        Start-Sleep -Seconds 60
        UsoClient StartDownload
        Start-Sleep -Seconds 60

    - name: Windows frissítések telepítése
      ansible.windows.win_updates:
        category_names: '*'
        server_selection: windows_update
        reboot: true
        reboot_timeout: 3600
      register: update_result

    - name: Update eredmény kiírása
      debug:
        var: update_result
