---
- name: Windows Update debug
  hosts: all
  gather_facts: false

  tasks:
    - name: Windows frissítések telepítése
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
        reboot_timeout: 3600
      register: update_result

    - name: Update eredmény kiírása
      debug:
        var: update_result
